name: Build & Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v3
      - name: Using Node.js
        run: actions/setup-node@v2
        with:
          node-version: 16.
        - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test